vich_uploader:
    db_driver: orm

    mappings:
        flickr:
            uri_prefix: /images/flickr
            upload_destination: '%kernel.project_dir%/public/images/flickr'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
